########################### Default configuration ######################
baseURL = "https://cloudnative.to/"
title = "Cloud Native Community"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
# disqusShortname = "bexer" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
hasCJKLanguage = true
DefaultContentLanguage = "zh"

[outputs]
home = ["HTML", "RSS", "JSON"]

############################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

########################### navigation ################################
# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 2

#[[menu.main]]
#name = "Service"
#URL = "service"
#weight = 3

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[menu.main]]
name = "Team"
URL = "team"
weight = 6

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7

# [[menu.main]]
# weight = 8
# name = "Pages"
# hasChildren = true
#
#   [[menu.main]]
#   parent = "Pages"
#   name = "Project"
#   URL = "project"

# footer menu
[[menu.footer]]
name = "Terms of Service"
URL = "terms"
weight = 1

[[menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 2

########################### Default parameters ######################
[params]
logo = "images/logo.png"
logo_footer = "images/logo-alt.png"
# top header
top_header = false
# Meta data
description = "Slogan"
author = "Cloud Native Community"
# contact info
wechat_qrcode= "images/wechat-qrcode.jpg"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-93485976-4" # your id
# page sidebar quick contact form
quick_contact = true
# search
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Join us"
link = "contact"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

########################### social icon ############################
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/cloudnativeto"

[[params.social]]
icon = "fa-github"
link = "https://github.com/cloudnativeto"

[[params.social]]
icon = "fa-wechat"
# change the link after the public announcement
link = "/contact"

[[params.social]]
icon = "fa-rss"
link = "https://cloudnative.to/blog/index.xml"

################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 2
#home = "Home"
# footer content
footer_content = "云原生社区是一个有温度的开源社区。它由一群热爱开源的行业精英自发成立，秉持“共识、共治、共建”的原则。社区的宗旨是：连接、中立、开源。即连接国内外社区，企业中立，且关注开源、立足开源、反馈开源。"
# copyright
copyright = "Copyright &copy; 2020 Cloud Native Community"


################################### Chinese language #####################################
[Languages.zh]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/zh"
weight = 1
#home = "主页"
# footer content
footer_content = "云原生社区是一个有温度的开源社区。它由一群热爱开源的行业精英自发成立，秉持“共识、共治、共建”的原则。社区的宗旨是：连接、中立、开源。即连接国内外社区，企业中立，且关注开源、立足开源、反馈开源。"
# copyright
copyright = "Copyright &copy; 2020 云原生社区"

########################### Chinese navigation ################################
# main menu
[[Languages.zh.menu.main]]
name = "关于"
URL = "about"
weight = 2

#[[Languages.zh.menu.main]]
#name = "服务"
#URL = "service"
#weight = 3

[[Languages.zh.menu.main]]
name = "博客"
URL = "blog"
weight = 4

[[Languages.zh.menu.main]]
name = "团队"
URL = "team"
weight = 6

[[Languages.zh.menu.main]]
name = "联系"
URL = "contact"
weight = 7

# [[Languages.zh.menu.main]]
# weight = 8
# name = "页面"
# hasChildren = true
#
#   [[Languages.zh.menu.main]]
#   parent = "页面"
#   name = "项目"
#   URL = "project"

# footer menu
[[Languages.zh.menu.footer]]
name = "服务条款"
URL = "terms"
weight = 1

[[Languages.zh.menu.ooter]]
name = "隐私政策"
URL = "privacy-policy"
weight = 2
